# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convertor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 466)
        MainWindow.setMaximumSize(QtCore.QSize(675, 466))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 #0F2027, stop:0.5 #203A43, stop:1 #24243e);\n"
            "\n"
            "\n"
            "border-radius:5px;")
        self.centralwidget.setObjectName("centralwidget")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(626, 11, 41, 21))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                "border-radius:10px;")
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.minimize = QtWidgets.QPushButton(self.centralwidget)
        self.minimize.setGeometry(QtCore.QRect(576, 11, 41, 21))
        self.minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize.setStyleSheet("background-color: rgb(232, 232, 0);\n"
                                    "border-radius:10px;")
        self.minimize.setText("")
        self.minimize.setObjectName("minimize")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 60, 671, 401))
        self.stackedWidget.setStyleSheet("border-radius:5px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.home_label = QtWidgets.QLabel(self.page)
        self.home_label.setGeometry(QtCore.QRect(230, 30, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setItalic(True)
        self.home_label.setFont(font)
        self.home_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "background-color:none;\n"
                                      "border:1px solid white;")
        self.home_label.setAlignment(QtCore.Qt.AlignCenter)
        self.home_label.setObjectName("home_label")
        self.btn_mp4_mp3 = QtWidgets.QPushButton(self.page)
        self.btn_mp4_mp3.setGeometry(QtCore.QRect(40, 110, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_mp4_mp3.setFont(font)
        self.btn_mp4_mp3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_mp4_mp3.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(20, 42, 84);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:6px;\n"
                                       "}")
        self.btn_mp4_mp3.setObjectName("btn_mp4_mp3")
        self.btn_jpg_png = QtWidgets.QPushButton(self.page)
        self.btn_jpg_png.setGeometry(QtCore.QRect(190, 110, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_jpg_png.setFont(font)
        self.btn_jpg_png.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_jpg_png.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(20, 42, 84);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:6px;\n"
                                       "}")
        self.btn_jpg_png.setObjectName("btn_jpg_png")
        self.btn_png_jpg = QtWidgets.QPushButton(self.page)
        self.btn_png_jpg.setGeometry(QtCore.QRect(340, 110, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_png_jpg.setFont(font)
        self.btn_png_jpg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_png_jpg.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(20, 42, 84);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:6px;\n"
                                       "}")
        self.btn_png_jpg.setObjectName("btn_png_jpg")
        self.btn_setting = QtWidgets.QPushButton(self.page)
        self.btn_setting.setGeometry(QtCore.QRect(490, 110, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_setting.setFont(font)
        self.btn_setting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_setting.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(20, 42, 84);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:6px;\n"
                                       "}")
        self.btn_setting.setObjectName("btn_setting")
        self.stackedWidget.addWidget(self.page)
        self.mp4tomp3 = QtWidgets.QWidget()
        self.mp4tomp3.setObjectName("mp4tomp3")
        self.fileaddress_label_mp4_mp3 = QtWidgets.QLabel(self.mp4tomp3)
        self.fileaddress_label_mp4_mp3.setGeometry(QtCore.QRect(20, 70, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.fileaddress_label_mp4_mp3.setFont(font)
        self.fileaddress_label_mp4_mp3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                     "background-color:none;")
        self.fileaddress_label_mp4_mp3.setAlignment(QtCore.Qt.AlignCenter)
        self.fileaddress_label_mp4_mp3.setObjectName("fileaddress_label_mp4_mp3")
        self.label_mp4_mp3 = QtWidgets.QLabel(self.mp4tomp3)
        self.label_mp4_mp3.setGeometry(QtCore.QRect(210, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_mp4_mp3.setFont(font)
        self.label_mp4_mp3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color:none;\n"
                                         "border:1px solid white;")
        self.label_mp4_mp3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mp4_mp3.setObjectName("label_mp4_mp3")
        self.mp4_mp3_lineEdit_address = QtWidgets.QLineEdit(self.mp4tomp3)
        self.mp4_mp3_lineEdit_address.setGeometry(QtCore.QRect(172, 83, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.mp4_mp3_lineEdit_address.setFont(font)
        self.mp4_mp3_lineEdit_address.setStyleSheet("border-radius:10px;\n"
                                                    "background-color: rgb(255, 255, 255);")
        self.mp4_mp3_lineEdit_address.setObjectName("mp4_mp3_lineEdit_address")
        self.btn_browse_mp4_mp3_address = QtWidgets.QPushButton(self.mp4tomp3)
        self.btn_browse_mp4_mp3_address.setGeometry(QtCore.QRect(560, 79, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.btn_browse_mp4_mp3_address.setFont(font)
        self.btn_browse_mp4_mp3_address.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse_mp4_mp3_address.setStyleSheet("QPushButton{\n"
                                                      "    background-color: rgb(95, 95, 95);\n"
                                                      "    color: rgb(255, 255, 255);\n"
                                                      "border-radius:10px;\n"
                                                      "}\n"
                                                      "\n"
                                                      "QPushButton:hover{\n"
                                                      "background-color: rgb(118, 118, 118);\n"
                                                      "border-radius:6px;\n"
                                                      "\n"
                                                      "}")
        self.btn_browse_mp4_mp3_address.setObjectName("btn_browse_mp4_mp3_address")
        self.savefile_label_mp4_mp3 = QtWidgets.QLabel(self.mp4tomp3)
        self.savefile_label_mp4_mp3.setGeometry(QtCore.QRect(20, 138, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.savefile_label_mp4_mp3.setFont(font)
        self.savefile_label_mp4_mp3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                  "background-color:none;")
        self.savefile_label_mp4_mp3.setAlignment(QtCore.Qt.AlignCenter)
        self.savefile_label_mp4_mp3.setObjectName("savefile_label_mp4_mp3")
        self.mp4_mp3_lineEdit_save = QtWidgets.QLineEdit(self.mp4tomp3)
        self.mp4_mp3_lineEdit_save.setGeometry(QtCore.QRect(136, 153, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.mp4_mp3_lineEdit_save.setFont(font)
        self.mp4_mp3_lineEdit_save.setStyleSheet("border-radius:10px;\n"
                                                 "background-color: rgb(255, 255, 255);")
        self.mp4_mp3_lineEdit_save.setObjectName("mp4_mp3_lineEdit_save")
        self.btn_browse_mp4_mp3_save = QtWidgets.QPushButton(self.mp4tomp3)
        self.btn_browse_mp4_mp3_save.setGeometry(QtCore.QRect(531, 147, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.btn_browse_mp4_mp3_save.setFont(font)
        self.btn_browse_mp4_mp3_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse_mp4_mp3_save.setStyleSheet("QPushButton{\n"
                                                   "    background-color: rgb(95, 95, 95);\n"
                                                   "    color: rgb(255, 255, 255);\n"
                                                   "border-radius:10px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "QPushButton:hover{\n"
                                                   "background-color: rgb(118, 118, 118);\n"
                                                   "border-radius:6px;\n"
                                                   "\n"
                                                   "}")
        self.btn_browse_mp4_mp3_save.setObjectName("btn_browse_mp4_mp3_save")
        self.name_label_mp4_mp3 = QtWidgets.QLabel(self.mp4tomp3)
        self.name_label_mp4_mp3.setGeometry(QtCore.QRect(20, 207, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.name_label_mp4_mp3.setFont(font)
        self.name_label_mp4_mp3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "background-color:none;")
        self.name_label_mp4_mp3.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label_mp4_mp3.setObjectName("name_label_mp4_mp3")
        self.mp4_mp3_lineEdit_name = QtWidgets.QLineEdit(self.mp4tomp3)
        self.mp4_mp3_lineEdit_name.setGeometry(QtCore.QRect(124, 220, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.mp4_mp3_lineEdit_name.setFont(font)
        self.mp4_mp3_lineEdit_name.setStyleSheet("border-radius:10px;\n"
                                                 "background-color: rgb(255, 255, 255);")
        self.mp4_mp3_lineEdit_name.setAlignment(QtCore.Qt.AlignCenter)
        self.mp4_mp3_lineEdit_name.setObjectName("mp4_mp3_lineEdit_name")
        self.time_label_mp4_mp3_2 = QtWidgets.QLabel(self.mp4tomp3)
        self.time_label_mp4_mp3_2.setGeometry(QtCore.QRect(20, 272, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.time_label_mp4_mp3_2.setFont(font)
        self.time_label_mp4_mp3_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                "background-color:none;")
        self.time_label_mp4_mp3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_mp4_mp3_2.setObjectName("time_label_mp4_mp3_2")
        self.mp4_mp3_lineEdit_time = QtWidgets.QLineEdit(self.mp4tomp3)
        self.mp4_mp3_lineEdit_time.setGeometry(QtCore.QRect(115, 285, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.mp4_mp3_lineEdit_time.setFont(font)
        self.mp4_mp3_lineEdit_time.setStyleSheet("border-radius:10px;\n"
                                                 "background-color: rgb(255, 255, 255);")
        self.mp4_mp3_lineEdit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.mp4_mp3_lineEdit_time.setObjectName("mp4_mp3_lineEdit_time")
        self.size_label_mp4_mp3 = QtWidgets.QLabel(self.mp4tomp3)
        self.size_label_mp4_mp3.setGeometry(QtCore.QRect(355, 207, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.size_label_mp4_mp3.setFont(font)
        self.size_label_mp4_mp3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "background-color:none;")
        self.size_label_mp4_mp3.setAlignment(QtCore.Qt.AlignCenter)
        self.size_label_mp4_mp3.setObjectName("size_label_mp4_mp3")
        self.mp4_mp3_lineEdit_size = QtWidgets.QLineEdit(self.mp4tomp3)
        self.mp4_mp3_lineEdit_size.setGeometry(QtCore.QRect(440, 220, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.mp4_mp3_lineEdit_size.setFont(font)
        self.mp4_mp3_lineEdit_size.setStyleSheet("border-radius:10px;\n"
                                                 "background-color: rgb(255, 255, 255);")
        self.mp4_mp3_lineEdit_size.setAlignment(QtCore.Qt.AlignCenter)
        self.mp4_mp3_lineEdit_size.setObjectName("mp4_mp3_lineEdit_size")
        self.btn_mp4_mp3_convert = QtWidgets.QPushButton(self.mp4tomp3)
        self.btn_mp4_mp3_convert.setGeometry(QtCore.QRect(530, 350, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_mp4_mp3_convert.setFont(font)
        self.btn_mp4_mp3_convert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_mp4_mp3_convert.setStyleSheet("QPushButton{\n"
                                               "    background-color: rgb(20, 42, 84);\n"
                                               "    color: rgb(255, 255, 255);\n"
                                               "border-radius:10px;\n"
                                               "}\n"
                                               "QPushButton:hover{\n"
                                               "    background-color: rgb(95, 95, 95);\n"
                                               "border-radius:6px;\n"
                                               "}")
        self.btn_mp4_mp3_convert.setObjectName("btn_mp4_mp3_convert")
        self.btn_mp4_mp3_clear = QtWidgets.QPushButton(self.mp4tomp3)
        self.btn_mp4_mp3_clear.setGeometry(QtCore.QRect(380, 350, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_mp4_mp3_clear.setFont(font)
        self.btn_mp4_mp3_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_mp4_mp3_clear.setStyleSheet("QPushButton{\n"
                                             "    background-color: rgb(20, 42, 84);\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "border-radius:10px;\n"
                                             "}\n"
                                             "QPushButton:hover{\n"
                                             "    background-color: rgb(95, 95, 95);\n"
                                             "border-radius:6px;\n"
                                             "}")
        self.btn_mp4_mp3_clear.setObjectName("btn_mp4_mp3_clear")
        self.process_label = QtWidgets.QLabel(self.mp4tomp3)
        self.process_label.setGeometry(QtCore.QRect(30, 340, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setItalic(True)
        self.process_label.setFont(font)
        self.process_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color:none;")
        self.process_label.setAlignment(QtCore.Qt.AlignCenter)
        self.process_label.setObjectName("process_label")
        self.newsize_label_mp4_mp3 = QtWidgets.QLabel(self.mp4tomp3)
        self.newsize_label_mp4_mp3.setGeometry(QtCore.QRect(355, 270, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.newsize_label_mp4_mp3.setFont(font)
        self.newsize_label_mp4_mp3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                 "background-color:none;")
        self.newsize_label_mp4_mp3.setAlignment(QtCore.Qt.AlignCenter)
        self.newsize_label_mp4_mp3.setObjectName("newsize_label_mp4_mp3")
        self.mp4_mp3_lineEdit_newSize = QtWidgets.QLineEdit(self.mp4tomp3)
        self.mp4_mp3_lineEdit_newSize.setGeometry(QtCore.QRect(484, 283, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.mp4_mp3_lineEdit_newSize.setFont(font)
        self.mp4_mp3_lineEdit_newSize.setStyleSheet("border-radius:10px;\n"
                                                    "background-color: rgb(255, 255, 255);")
        self.mp4_mp3_lineEdit_newSize.setAlignment(QtCore.Qt.AlignCenter)
        self.mp4_mp3_lineEdit_newSize.setObjectName("mp4_mp3_lineEdit_newSize")
        self.stackedWidget.addWidget(self.mp4tomp3)
        self.jpgtopng = QtWidgets.QWidget()
        self.jpgtopng.setObjectName("jpgtopng")
        self.btn_browse_jpg_png_address = QtWidgets.QPushButton(self.jpgtopng)
        self.btn_browse_jpg_png_address.setGeometry(QtCore.QRect(564, 77, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.btn_browse_jpg_png_address.setFont(font)
        self.btn_browse_jpg_png_address.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse_jpg_png_address.setStyleSheet("QPushButton{\n"
                                                      "    background-color: rgb(95, 95, 95);\n"
                                                      "    color: rgb(255, 255, 255);\n"
                                                      "border-radius:10px;\n"
                                                      "}\n"
                                                      "\n"
                                                      "QPushButton:hover{\n"
                                                      "background-color: rgb(118, 118, 118);\n"
                                                      "border-radius:6px;\n"
                                                      "\n"
                                                      "}")
        self.btn_browse_jpg_png_address.setObjectName("btn_browse_jpg_png_address")
        self.jpg_png_lineEdit_name = QtWidgets.QLineEdit(self.jpgtopng)
        self.jpg_png_lineEdit_name.setGeometry(QtCore.QRect(440, 213, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.jpg_png_lineEdit_name.setFont(font)
        self.jpg_png_lineEdit_name.setStyleSheet("border-radius:10px;\n"
                                                 "background-color: rgb(255, 255, 255);")
        self.jpg_png_lineEdit_name.setAlignment(QtCore.Qt.AlignCenter)
        self.jpg_png_lineEdit_name.setObjectName("jpg_png_lineEdit_name")
        self.jpg_png_lineEdit_address = QtWidgets.QLineEdit(self.jpgtopng)
        self.jpg_png_lineEdit_address.setGeometry(QtCore.QRect(174, 83, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.jpg_png_lineEdit_address.setFont(font)
        self.jpg_png_lineEdit_address.setStyleSheet("border-radius:10px;\n"
                                                    "background-color: rgb(255, 255, 255);")
        self.jpg_png_lineEdit_address.setObjectName("jpg_png_lineEdit_address")
        self.btn_browse_jpg_png_save = QtWidgets.QPushButton(self.jpgtopng)
        self.btn_browse_jpg_png_save.setGeometry(QtCore.QRect(532, 142, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.btn_browse_jpg_png_save.setFont(font)
        self.btn_browse_jpg_png_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse_jpg_png_save.setStyleSheet("QPushButton{\n"
                                                   "    background-color: rgb(95, 95, 95);\n"
                                                   "    color: rgb(255, 255, 255);\n"
                                                   "border-radius:10px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "QPushButton:hover{\n"
                                                   "background-color: rgb(118, 118, 118);\n"
                                                   "border-radius:6px;\n"
                                                   "\n"
                                                   "}")
        self.btn_browse_jpg_png_save.setObjectName("btn_browse_jpg_png_save")
        self.save_label_jpg_png = QtWidgets.QLabel(self.jpgtopng)
        self.save_label_jpg_png.setGeometry(QtCore.QRect(20, 133, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.save_label_jpg_png.setFont(font)
        self.save_label_jpg_png.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "background-color:none;")
        self.save_label_jpg_png.setAlignment(QtCore.Qt.AlignCenter)
        self.save_label_jpg_png.setObjectName("save_label_jpg_png")
        self.fileaddress_label_jpg_png_2 = QtWidgets.QLabel(self.jpgtopng)
        self.fileaddress_label_jpg_png_2.setGeometry(QtCore.QRect(20, 70, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.fileaddress_label_jpg_png_2.setFont(font)
        self.fileaddress_label_jpg_png_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                       "background-color:none;")
        self.fileaddress_label_jpg_png_2.setAlignment(QtCore.Qt.AlignCenter)
        self.fileaddress_label_jpg_png_2.setObjectName("fileaddress_label_jpg_png_2")
        self.jpg_png_lineEdit_save = QtWidgets.QLineEdit(self.jpgtopng)
        self.jpg_png_lineEdit_save.setGeometry(QtCore.QRect(137, 147, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.jpg_png_lineEdit_save.setFont(font)
        self.jpg_png_lineEdit_save.setStyleSheet("border-radius:10px;\n"
                                                 "background-color: rgb(255, 255, 255);")
        self.jpg_png_lineEdit_save.setObjectName("jpg_png_lineEdit_save")
        self.name_label_jpg_png = QtWidgets.QLabel(self.jpgtopng)
        self.name_label_jpg_png.setGeometry(QtCore.QRect(341, 199, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.name_label_jpg_png.setFont(font)
        self.name_label_jpg_png.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "background-color:none;")
        self.name_label_jpg_png.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label_jpg_png.setObjectName("name_label_jpg_png")
        self.label_jpg_png = QtWidgets.QLabel(self.jpgtopng)
        self.label_jpg_png.setGeometry(QtCore.QRect(210, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_jpg_png.setFont(font)
        self.label_jpg_png.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color:none;\n"
                                         "border:1px solid white;")
        self.label_jpg_png.setAlignment(QtCore.Qt.AlignCenter)
        self.label_jpg_png.setObjectName("label_jpg_png")
        self.photo_jpg_png = QtWidgets.QLabel(self.jpgtopng)
        self.photo_jpg_png.setGeometry(QtCore.QRect(10, 200, 321, 191))
        self.photo_jpg_png.setText("")
        self.photo_jpg_png.setObjectName("photo_jpg_png")
        self.btn_clear_jpg_png = QtWidgets.QPushButton(self.jpgtopng)
        self.btn_clear_jpg_png.setGeometry(QtCore.QRect(380, 350, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_clear_jpg_png.setFont(font)
        self.btn_clear_jpg_png.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clear_jpg_png.setStyleSheet("QPushButton{\n"
                                             "    background-color: rgb(20, 42, 84);\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "border-radius:10px;\n"
                                             "}\n"
                                             "QPushButton:hover{\n"
                                             "    background-color: rgb(95, 95, 95);\n"
                                             "border-radius:6px;\n"
                                             "}")
        self.btn_clear_jpg_png.setObjectName("btn_clear_jpg_png")
        self.btn_convert_jpg_png = QtWidgets.QPushButton(self.jpgtopng)
        self.btn_convert_jpg_png.setGeometry(QtCore.QRect(530, 350, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_convert_jpg_png.setFont(font)
        self.btn_convert_jpg_png.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_convert_jpg_png.setStyleSheet("QPushButton{\n"
                                               "    background-color: rgb(20, 42, 84);\n"
                                               "    color: rgb(255, 255, 255);\n"
                                               "border-radius:10px;\n"
                                               "}\n"
                                               "QPushButton:hover{\n"
                                               "    background-color: rgb(95, 95, 95);\n"
                                               "border-radius:6px;\n"
                                               "}")
        self.btn_convert_jpg_png.setObjectName("btn_convert_jpg_png")
        self.process_label_jpg_png = QtWidgets.QLabel(self.jpgtopng)
        self.process_label_jpg_png.setGeometry(QtCore.QRect(380, 270, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setItalic(True)
        self.process_label_jpg_png.setFont(font)
        self.process_label_jpg_png.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                 "background-color:none;")
        self.process_label_jpg_png.setAlignment(QtCore.Qt.AlignCenter)
        self.process_label_jpg_png.setObjectName("process_label_jpg_png")
        self.stackedWidget.addWidget(self.jpgtopng)
        self.pngtojpg = QtWidgets.QWidget()
        self.pngtojpg.setObjectName("pngtojpg")
        self.png_jpg_lineEdit_name = QtWidgets.QLineEdit(self.pngtojpg)
        self.png_jpg_lineEdit_name.setGeometry(QtCore.QRect(440, 213, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.png_jpg_lineEdit_name.setFont(font)
        self.png_jpg_lineEdit_name.setStyleSheet("border-radius:10px;\n"
                                                 "background-color: rgb(255, 255, 255);")
        self.png_jpg_lineEdit_name.setAlignment(QtCore.Qt.AlignCenter)
        self.png_jpg_lineEdit_name.setObjectName("png_jpg_lineEdit_name")
        self.save_label_png_jpg = QtWidgets.QLabel(self.pngtojpg)
        self.save_label_png_jpg.setGeometry(QtCore.QRect(20, 133, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.save_label_png_jpg.setFont(font)
        self.save_label_png_jpg.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "background-color:none;")
        self.save_label_png_jpg.setAlignment(QtCore.Qt.AlignCenter)
        self.save_label_png_jpg.setObjectName("save_label_png_jpg")
        self.photo_png_jpg = QtWidgets.QLabel(self.pngtojpg)
        self.photo_png_jpg.setGeometry(QtCore.QRect(10, 200, 321, 191))
        self.photo_png_jpg.setText("")
        self.photo_png_jpg.setObjectName("photo_png_jpg")
        self.fileaddress_label_png_jpg = QtWidgets.QLabel(self.pngtojpg)
        self.fileaddress_label_png_jpg.setGeometry(QtCore.QRect(20, 70, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.fileaddress_label_png_jpg.setFont(font)
        self.fileaddress_label_png_jpg.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                     "background-color:none;")
        self.fileaddress_label_png_jpg.setAlignment(QtCore.Qt.AlignCenter)
        self.fileaddress_label_png_jpg.setObjectName("fileaddress_label_png_jpg")
        self.btn_browse_png_jpg_address = QtWidgets.QPushButton(self.pngtojpg)
        self.btn_browse_png_jpg_address.setGeometry(QtCore.QRect(564, 77, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.btn_browse_png_jpg_address.setFont(font)
        self.btn_browse_png_jpg_address.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse_png_jpg_address.setStyleSheet("QPushButton{\n"
                                                      "    background-color: rgb(95, 95, 95);\n"
                                                      "    color: rgb(255, 255, 255);\n"
                                                      "border-radius:10px;\n"
                                                      "}\n"
                                                      "\n"
                                                      "QPushButton:hover{\n"
                                                      "background-color: rgb(118, 118, 118);\n"
                                                      "border-radius:6px;\n"
                                                      "\n"
                                                      "}")
        self.btn_browse_png_jpg_address.setObjectName("btn_browse_png_jpg_address")
        self.name_label_png_jpg = QtWidgets.QLabel(self.pngtojpg)
        self.name_label_png_jpg.setGeometry(QtCore.QRect(341, 199, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.name_label_png_jpg.setFont(font)
        self.name_label_png_jpg.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "background-color:none;")
        self.name_label_png_jpg.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label_png_jpg.setObjectName("name_label_png_jpg")
        self.btn_clear_png_jpg = QtWidgets.QPushButton(self.pngtojpg)
        self.btn_clear_png_jpg.setGeometry(QtCore.QRect(380, 350, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_clear_png_jpg.setFont(font)
        self.btn_clear_png_jpg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clear_png_jpg.setStyleSheet("QPushButton{\n"
                                             "    background-color: rgb(20, 42, 84);\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "border-radius:10px;\n"
                                             "}\n"
                                             "QPushButton:hover{\n"
                                             "    background-color: rgb(95, 95, 95);\n"
                                             "border-radius:6px;\n"
                                             "}")
        self.btn_clear_png_jpg.setObjectName("btn_clear_png_jpg")
        self.btn_convert_png_jpg = QtWidgets.QPushButton(self.pngtojpg)
        self.btn_convert_png_jpg.setGeometry(QtCore.QRect(530, 350, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_convert_png_jpg.setFont(font)
        self.btn_convert_png_jpg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_convert_png_jpg.setStyleSheet("QPushButton{\n"
                                               "    background-color: rgb(20, 42, 84);\n"
                                               "    color: rgb(255, 255, 255);\n"
                                               "border-radius:10px;\n"
                                               "}\n"
                                               "QPushButton:hover{\n"
                                               "    background-color: rgb(95, 95, 95);\n"
                                               "border-radius:6px;\n"
                                               "}")
        self.btn_convert_png_jpg.setObjectName("btn_convert_png_jpg")
        self.btn_browse_png_jpg_save = QtWidgets.QPushButton(self.pngtojpg)
        self.btn_browse_png_jpg_save.setGeometry(QtCore.QRect(532, 142, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.btn_browse_png_jpg_save.setFont(font)
        self.btn_browse_png_jpg_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse_png_jpg_save.setStyleSheet("QPushButton{\n"
                                                   "    background-color: rgb(95, 95, 95);\n"
                                                   "    color: rgb(255, 255, 255);\n"
                                                   "border-radius:10px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "QPushButton:hover{\n"
                                                   "background-color: rgb(118, 118, 118);\n"
                                                   "border-radius:6px;\n"
                                                   "\n"
                                                   "}")
        self.btn_browse_png_jpg_save.setObjectName("btn_browse_png_jpg_save")
        self.png_jpg_lineEdit_address = QtWidgets.QLineEdit(self.pngtojpg)
        self.png_jpg_lineEdit_address.setGeometry(QtCore.QRect(174, 83, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.png_jpg_lineEdit_address.setFont(font)
        self.png_jpg_lineEdit_address.setStyleSheet("border-radius:10px;\n"
                                                    "background-color: rgb(255, 255, 255);")
        self.png_jpg_lineEdit_address.setObjectName("png_jpg_lineEdit_address")
        self.label_png_jpg = QtWidgets.QLabel(self.pngtojpg)
        self.label_png_jpg.setGeometry(QtCore.QRect(210, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_png_jpg.setFont(font)
        self.label_png_jpg.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color:none;\n"
                                         "border:1px solid white;")
        self.label_png_jpg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_png_jpg.setObjectName("label_png_jpg")
        self.png_jpg_lineEdit_save = QtWidgets.QLineEdit(self.pngtojpg)
        self.png_jpg_lineEdit_save.setGeometry(QtCore.QRect(137, 147, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.png_jpg_lineEdit_save.setFont(font)
        self.png_jpg_lineEdit_save.setStyleSheet("border-radius:10px;\n"
                                                 "background-color: rgb(255, 255, 255);")
        self.png_jpg_lineEdit_save.setObjectName("png_jpg_lineEdit_save")
        self.process_label_png_jpg = QtWidgets.QLabel(self.pngtojpg)
        self.process_label_png_jpg.setGeometry(QtCore.QRect(380, 270, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setItalic(True)
        self.process_label_png_jpg.setFont(font)
        self.process_label_png_jpg.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                 "background-color:none;")
        self.process_label_png_jpg.setAlignment(QtCore.Qt.AlignCenter)
        self.process_label_png_jpg.setObjectName("process_label_png_jpg")
        self.stackedWidget.addWidget(self.pngtojpg)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_setting = QtWidgets.QLabel(self.page_4)
        self.label_setting.setGeometry(QtCore.QRect(236, 10, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_setting.setFont(font)
        self.label_setting.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color:none;\n"
                                         "border:1px solid white;")
        self.label_setting.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setting.setObjectName("label_setting")
        self.frame_info = QtWidgets.QFrame(self.page_4)
        self.frame_info.setGeometry(QtCore.QRect(20, 80, 341, 171))
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.label_info = QtWidgets.QLabel(self.frame_info)
        self.label_info.setGeometry(QtCore.QRect(10, 10, 291, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_info.setFont(font)
        self.label_info.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "background-color:none;")
        self.label_info.setObjectName("label_info")
        self.btn_info = QtWidgets.QPushButton(self.page_4)
        self.btn_info.setGeometry(QtCore.QRect(540, 90, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_info.setFont(font)
        self.btn_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_info.setStyleSheet("QPushButton{\n"
                                    "    background-color: rgb(20, 42, 84);\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "border-radius:10px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(95, 95, 95);\n"
                                    "border-radius:6px;\n"
                                    "}")
        self.btn_info.setObjectName("btn_info")
        self.btn_theme = QtWidgets.QPushButton(self.page_4)
        self.btn_theme.setGeometry(QtCore.QRect(400, 90, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_theme.setFont(font)
        self.btn_theme.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_theme.setStyleSheet("QPushButton{\n"
                                     "    background-color: rgb(20, 42, 84);\n"
                                     "    color: rgb(255, 255, 255);\n"
                                     "border-radius:10px;\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "    background-color: rgb(95, 95, 95);\n"
                                     "border-radius:6px;\n"
                                     "}")
        self.btn_theme.setObjectName("btn_theme")
        self.theme_frame = QtWidgets.QFrame(self.page_4)
        self.theme_frame.setGeometry(QtCore.QRect(20, 260, 341, 131))
        self.theme_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.theme_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.theme_frame.setObjectName("theme_frame")
        self.theme_1 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_1.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.theme_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_1.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #304352, stop:1 #d7d2cc);\n"
            "border-radius:5px;\n"
            "")
        self.theme_1.setText("")
        self.theme_1.setObjectName("theme_1")
        self.theme_3 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_3.setGeometry(QtCore.QRect(240, 10, 91, 31))
        self.theme_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_3.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #aa4b6b, stop:0.5 #6b6b83, stop:1 #3b8d99);")
        self.theme_3.setText("")
        self.theme_3.setObjectName("theme_3")
        self.theme_2 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_2.setGeometry(QtCore.QRect(127, 10, 91, 31))
        self.theme_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #654ea3, stop:1 #eaafc8); ")
        self.theme_2.setText("")
        self.theme_2.setObjectName("theme_2")
        self.theme_4 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_4.setGeometry(QtCore.QRect(10, 70, 91, 31))
        self.theme_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_4.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #8A2387, stop:0.5 #E94057, stop:1 #F27121);")
        self.theme_4.setText("")
        self.theme_4.setObjectName("theme_4")
        self.theme_6 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_6.setGeometry(QtCore.QRect(240, 70, 91, 31))
        self.theme_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_6.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #636363,stop:1 #a2ab58);")
        self.theme_6.setText("")
        self.theme_6.setObjectName("theme_6")
        self.theme_5 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_5.setGeometry(QtCore.QRect(127, 70, 91, 31))
        self.theme_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_5.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 #0F2027, stop:0.5 #203A43, stop:1 #24243e);\n"
            "")
        self.theme_5.setText("")
        self.theme_5.setObjectName("theme_5")
        self.btn_language = QtWidgets.QPushButton(self.page_4)
        self.btn_language.setGeometry(QtCore.QRect(540, 150, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_language.setFont(font)
        self.btn_language.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_language.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(20, 42, 84);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(95, 95, 95);\n"
                                        "border-radius:6px;\n"
                                        "}")
        self.btn_language.setObjectName("btn_language")
        self.language_frame = QtWidgets.QFrame(self.page_4)
        self.language_frame.setGeometry(QtCore.QRect(370, 260, 291, 131))
        self.language_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.language_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.language_frame.setObjectName("language_frame")
        self.btn_english = QtWidgets.QPushButton(self.language_frame)
        self.btn_english.setGeometry(QtCore.QRect(10, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_english.setFont(font)
        self.btn_english.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_english.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(20, 42, 84);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:6px;\n"
                                       "}")
        self.btn_english.setObjectName("btn_english")
        self.btn_persian = QtWidgets.QPushButton(self.language_frame)
        self.btn_persian.setGeometry(QtCore.QRect(152, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_persian.setFont(font)
        self.btn_persian.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_persian.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(20, 42, 84);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:6px;\n"
                                       "}")
        self.btn_persian.setObjectName("btn_persian")
        self.btn_germany = QtWidgets.QPushButton(self.language_frame)
        self.btn_germany.setGeometry(QtCore.QRect(10, 70, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_germany.setFont(font)
        self.btn_germany.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_germany.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(20, 42, 84);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:6px;\n"
                                       "}")
        self.btn_germany.setObjectName("btn_germany")
        self.btn_russian = QtWidgets.QPushButton(self.language_frame)
        self.btn_russian.setGeometry(QtCore.QRect(152, 70, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_russian.setFont(font)
        self.btn_russian.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_russian.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(20, 42, 84);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:6px;\n"
                                       "}")
        self.btn_russian.setObjectName("btn_russian")
        self.stackedWidget.addWidget(self.page_4)
        self.btn_home = QtWidgets.QPushButton(self.centralwidget)
        self.btn_home.setGeometry(QtCore.QRect(10, 8, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_home.setFont(font)
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_home.setStyleSheet("QPushButton{\n"
                                    "    background-color: rgb(20, 42, 84);\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "border-radius:10px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(95, 95, 95);\n"
                                    "border-radius:6px;\n"
                                    "}")
        self.btn_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("2x/outline_home_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon)
        self.btn_home.setIconSize(QtCore.QSize(32, 32))
        self.btn_home.setObjectName("btn_home")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.exit.clicked.connect(MainWindow.close)
        self.minimize.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home_label.setText(_translate("MainWindow", "Welcome"))
        self.btn_mp4_mp3.setText(_translate("MainWindow", "Mp4 to Mp3"))
        self.btn_jpg_png.setText(_translate("MainWindow", "Jpg to Png"))
        self.btn_png_jpg.setText(_translate("MainWindow", "Png to Jpg"))
        self.btn_setting.setText(_translate("MainWindow", "Setting"))
        self.fileaddress_label_mp4_mp3.setText(_translate("MainWindow", "File address :"))
        self.label_mp4_mp3.setText(_translate("MainWindow", "Convert Mp4 to Mp3"))
        self.btn_browse_mp4_mp3_address.setText(_translate("MainWindow", "Choose"))
        self.savefile_label_mp4_mp3.setText(_translate("MainWindow", "Save as  :"))
        self.btn_browse_mp4_mp3_save.setText(_translate("MainWindow", "Choose"))
        self.name_label_mp4_mp3.setText(_translate("MainWindow", "Name  :"))
        self.time_label_mp4_mp3_2.setText(_translate("MainWindow", "Time  :"))
        self.size_label_mp4_mp3.setText(_translate("MainWindow", "Size  :"))
        self.btn_mp4_mp3_convert.setText(_translate("MainWindow", "Convert"))
        self.btn_mp4_mp3_clear.setText(_translate("MainWindow", "Clear"))
        self.process_label.setText(_translate("MainWindow", "Time  :"))
        self.newsize_label_mp4_mp3.setText(_translate("MainWindow", "New size  :"))
        self.btn_browse_jpg_png_address.setText(_translate("MainWindow", "Choose"))
        self.btn_browse_jpg_png_save.setText(_translate("MainWindow", "Choose"))
        self.save_label_jpg_png.setText(_translate("MainWindow", "Save as  :"))
        self.fileaddress_label_jpg_png_2.setText(_translate("MainWindow", "File address :"))
        self.name_label_jpg_png.setText(_translate("MainWindow", "Name  :"))
        self.label_jpg_png.setText(_translate("MainWindow", "Convert Jpg to Png"))
        self.btn_clear_jpg_png.setText(_translate("MainWindow", "Clear"))
        self.btn_convert_jpg_png.setText(_translate("MainWindow", "Convert"))
        self.process_label_jpg_png.setText(_translate("MainWindow", "Time  :"))
        self.save_label_png_jpg.setText(_translate("MainWindow", "Save as  :"))
        self.fileaddress_label_png_jpg.setText(_translate("MainWindow", "File address :"))
        self.btn_browse_png_jpg_address.setText(_translate("MainWindow", "Choose"))
        self.name_label_png_jpg.setText(_translate("MainWindow", "Name  :"))
        self.btn_clear_png_jpg.setText(_translate("MainWindow", "Clear"))
        self.btn_convert_png_jpg.setText(_translate("MainWindow", "Convert"))
        self.btn_browse_png_jpg_save.setText(_translate("MainWindow", "Choose"))
        self.label_png_jpg.setText(_translate("MainWindow", "Convert Png to Jpg"))
        self.process_label_png_jpg.setText(_translate("MainWindow", "Time  :"))
        self.label_setting.setText(_translate("MainWindow", "Setting"))
        self.label_info.setText(_translate("MainWindow", "Powered by : Sajjad fani\n"
                                                         "Language : Python 3.9\n"
                                                         "Telegram ID : @sajad_fani\n"
                                                         "Email : faniam321@gmail.com"))
        self.btn_info.setText(_translate("MainWindow", "Info"))
        self.btn_theme.setText(_translate("MainWindow", "Theme"))
        self.theme_1.setToolTip(_translate("MainWindow", "Theme 1"))
        self.theme_3.setToolTip(_translate("MainWindow", "Theme 3"))
        self.theme_2.setToolTip(_translate("MainWindow", "Theme 2"))
        self.theme_4.setToolTip(_translate("MainWindow", "Theme 4"))
        self.theme_6.setToolTip(_translate("MainWindow", "Theme 6"))
        self.theme_5.setToolTip(_translate("MainWindow", "Theme 5"))
        self.btn_language.setText(_translate("MainWindow", "Language"))
        self.btn_english.setText(_translate("MainWindow", "English"))
        self.btn_persian.setText(_translate("MainWindow", "Persian"))
        self.btn_germany.setText(_translate("MainWindow", "Germany"))
        self.btn_russian.setText(_translate("MainWindow", "Russian"))
        self.btn_home.setToolTip(_translate("MainWindow", "Home"))
